### ISSUE TITLE
Selecting 240p quality -> The getter 'inSeconds' was called on null.

### ISSUE THREAD

**Issue by ghost** [prilogy/vimeo_player#28]
The example app. Tested with video id == 552414513. All other quality settings work.
```
The following NoSuchMethodError was thrown building FutureBuilder<void>(dirty, dependencies: [MediaQuery], state: _FutureBuilderState<void>#bd405):
The getter 'inSeconds' was called on null.
Receiver: null
Tried calling: inSeconds

The relevant error-causing widget was
VimeoPlayer
When the exception was thrown, this was the stack
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      _VimeoPlayerState.build.<anonymous closure>    package:vimeoplayer/vimeoplayer.dart:128
#2      _FutureBuilderState.build    package:flutter/…/widgets/async.dart:773
#3      StatefulElement.build    package:flutter/…/widgets/framework.dart:4612
...
```

**Comment by leonardmatasel** [comment]
You could try [omni_video_player](https://pub.dev/packages/omni_video_player). It handles Vimeo and other video sources more reliably and doesn’t require complex platform view setup
